name: Build NWA
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ARM Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi nodejs npm make
      - name: Build NWA
        run: make
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: echecs-numworks
          path: target/app.nwa
